In [1]:
import numpy as np

# Creation of Array :
- Step 1 : import numpy as np 
- Step 2 : var_name = np.array( [ list pass ] )

- > To check dimension of array : var_name.ndim
- > To check size (i.e. no. of elements in array ) : var_name.size 

- Shortcut to create a n-d array

```python
import numpy as np

arrn = np.array([1,2,3,4], ndmin=10)

```

In [ ]:
# Numpy array is Homogeneous


a = np.array([[1,2,3],[True,4,5],[0,1,4]])   # Typecast Boolean to int
print(a)


b = np.array([[1,2,3],[True,4,5],["Me",1,4]]) # Typecast everything  to str
print(b)


[[1 2 3]
 [1 4 5]
 [0 1 4]]
[['1' '2' '3']
 ['True' '4' '5']
 ['Me' '1' '4']]


In [3]:
# Multiplication

li = [1,2,3]
arr = np.array(li)

print("list multi : ", li*2)
print("array multi : ", arr*2)

list multi :  [1, 2, 3, 1, 2, 3]
array multi :  [2 4 6]


In [4]:
squares = [2,4,8,16,32,64]

squ_arr = np.array(squares)

print(squ_arr, type(squ_arr))

# check dimension
print(squ_arr.ndim)


# check size 
print(squ_arr.size)

[ 2  4  8 16 32 64] <class 'numpy.ndarray'>
1
6


In [5]:
# Create a n-d array 

squ_5arr = np.array(squares,ndmin=5)

print(squ_5arr,squ_5arr.ndim, squ_5arr.shape)

[[[[[ 2  4  8 16 32 64]]]]] 5 (1, 1, 1, 1, 6)


 # NumPy array with functions (special arrays): 

In [6]:
# 1. Create an array with a specific range 

range_array = np.arange(1,25,2)  # start stop step 
print(range_array)


# Build a 1-d array
# > will use reshape to make it to n-d further .

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [7]:
# 2. Create array with values that are spaced linearly at a specific interval

spaced_array = np.linspace(0,1,5) # start stop no._of_elements

print(spaced_array)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
# 3. logarithmic scale array 

log_array = np.logspace(1,3,5)  # 10^1 to 10^3 5 values 

print(log_array)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [9]:
#  4. array filled with zeroes or ones : 

zero_array = np.zeros([4])
print(zero_array)


# you can also define the dimension and number of elements like 
print()
# create array filled with zeros having 4 rows and 5 columns 


print(np.zeros([4,5], dtype=int))  # we can also define data type 

[0. 0. 0. 0.]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [10]:
print(np.ones(6))  # 1-d array

print()

print(np.ones([3,2,4]))

[1. 1. 1. 1. 1. 1.]

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [11]:
#  5 . Create array with our choice of value 

custom_arr = np.full([4,5],7)  # dimension [rows,col], value
print(custom_arr)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [12]:
# 6. Empty array : replace `.empty` with zeroes and pass dimension as same 

# It is uninitialised array
empty_arr =  np.empty(6,dtype=int)
print(empty_arr)


# > `Note `: In empty array it occupies the memory of previous build array in the memory if left unfiled .

[16843009 16843009 16843009 16843009 16843009 16843009]


In [13]:
# 7. identity matrix : 
# np.eye(dimension)
# It create a dimension x dimension identity matrix 


print(np.eye(4,4,dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## Array creation with Random numbers
- Random is a class containing various methods 

In [14]:
print(np.random.rand(10))

[0.99954961 0.94798885 0.48245358 0.67002147 0.560906   0.36813546
 0.98567983 0.54556095 0.7830325  0.68982637]


- Numpy provide you `random` module to work with random numbers.


In [15]:
print(np.random.rand(2,3))  # Don't provide square bracket as dimension it will be treated as list in random module 

[[0.89142162 0.50320678 0.23903797]
 [0.78270344 0.77345589 0.65360072]]


In [16]:
# 1. rand() : Returns a random float between 0 and 1.
# It generates the 1-d array of random value between 0 & 1 of number of elements provided .
# To generate a random array of n dimension just pass rows and coloumns in place of number of elements

var_name = np.random.rand(4,2)
print(var_name)


[[0.5100149  0.58406077]
 [0.71966886 0.73205707]
 [0.66469457 0.44777709]
 [0.13090779 0.42891412]]


In [17]:
# Q : Generate an array containing numbers from 0 to 1 and having 3-dimension with 3,4,2 elements 

print(np.random.rand(3,4,2))

[[[0.19556658 0.19239928]
  [0.2638134  0.57031678]
  [0.7827824  0.24249621]
  [0.8699466  0.75766227]]

 [[0.79307088 0.82548622]
  [0.52874571 0.01945773]
  [0.6484298  0.88456438]
  [0.00855098 0.96754033]]

 [[0.64080739 0.49995018]
  [0.44055108 0.94080341]
  [0.81895182 0.46058203]
  [0.93213768 0.27515372]]]


In [18]:
# Similiarly To generate a int in range randint(). 

print(np.random.randint(1,100, size=25))

#  generate a random integer array containing 3 rows and 5 elements in each row in b/w 1 to 10
print()
print(np.random.randint(1,11, size=(3,5)))

[ 7 59 59  9 10 46 17  7 31 33 53 77 77 77 92 64 39 27 85 22 70 86 49 31
  4]

[[ 7  3  4  9  3]
 [ 7  8  6  3  4]
 [ 3  7  7  7 10]]


In [19]:
# 2. randn() :  the function is used to generate random value close to zero . This may return possitive or negative value as well.
# random floats from standard normal distribution 

print(np.random.randn(2,4))

[[ 0.74709196  0.17991374  0.17653684 -0.90270045]
 [ 1.15553664  0.13028935  2.10784231  0.66144863]]
