# Common Data Types in NumPy:

- int32 , int64 : Integer types with different bit sizes.
- float32 ,float64 : Floating-point types with different precision.
- bool : Boolean data type.
- complex64 ,complex128 : Complex number types.
- object : For storing objects (e.g., Python objects, strings)

In [1]:
import numpy as np

In [2]:
# > To check data type of element or numpy array : var_name.dtype

arr = np.arange(3,28)

print(arr.dtype)

# To convert data types 

arr = np.arange(3,28,dtype=float) # this is typecasting 
print(arr.dtype)

int64
float64


In [3]:
# we can use astype() function to typecast : It does not changes the original array 
x = arr.astype(str)

print(x.dtype)

<U32


# Shaping & Reshaping : 
- Reshaping means changing the shape of an array.
- By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [4]:
# Convert the following 1-D array with 12 elements into a 2-D array.

# The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.arange(1,13)

print(arr.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
# Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

print(arr.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


>Note : We can reshape in any shape as long as elements are equal in both dimensions 

### `ravel()` & `flatten()` [copy or view]
- These are used to convert multi dimensional array to 1-d array
1. `ravel()` : ravel provides view any change in ravel array reflects in original array
2.  `flatten()` : flatten provides copy any change in flattens array does not reflect in original array
3. We can also pass -1 in reshape to convert in 1-d.

In [18]:
# ravel
arr1 = arr.reshape(2,3,2)
print(arr)
print(arr1)
new_arr = arr1.ravel()
print()
print(new_arr)

# change in array
new_arr[0]=100
print(arr1)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[100   2]
  [  3   4]
  [  5   6]]

 [[  7   8]
  [  9  10]
  [ 11  12]]]


In [21]:
# flatten 
arr2 = np.arange(1,21)
print(arr2)

arr3 = arr2.reshape(2,5,2)

print(arr3)
flat_arr = arr3.flatten()
print()
print(flat_arr)

# change 

flat_arr[0] = 100
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


In [26]:
new_arr1=np.array([[2,3,4],[3,4,5],[9,8,7]])
print(new_arr1)

new_arr2 = new_arr1.reshape(-1)
print(new_arr2)

new_arr2[0]=100
print(new_arr1)

[[2 3 4]
 [3 4 5]
 [9 8 7]]
[2 3 4 3 4 5 9 8 7]
[[100   3   4]
 [  3   4   5]
 [  9   8   7]]
